topics:
- /camera_array/cam0/image_raw
- /camera_array/cam1/image_raw
- /camera_array/cam2/image_raw
- /camera_array/cam3/image_raw
- /camera_array/cam4/image_raw
frequency: 1
viz : True
start_time: 0 # in seconds
end_time:  500  # in seconds
calib: True
board_rows: 16
board_cols: 9
invert: False
save_type: bmp

