#todo: Currently the script does not use the topics from config.yaml. It is hardcoded.
#camera_topics:
topics:
- /cam0/image_raw_bin1
- /cam0/image_raw_bin2
- /cam0/image_raw_bin4
- /imu/imu
#imu_topics:
base_camera_frequency:
- 160
base_imu_frequency:
- 400
downsampled_camera_frequency:  # in hz
- 20
- 40 
- 80
downsampled_imu_frequency:
- 400

file_name:
- vio_sync_exp_2000us_lab_3D

# Enter start_time and end_time as 0 
# if complete bag is to be analysed

#start_time: 0 # in seconds
#end_time: 10   # in seconds

