topics:
- /camera_array/cam0/image_raw
- /camera_array/cam1/image_raw
- /camera_array/cam2/image_raw
- /camera_array/cam3/image_raw
- /camera_array/cam4/image_raw
- /camera_array/cam5/image_raw
- /camera_array/cam6/image_raw

frequency: 1
start_time: 0 # in seconds
viz: false
end_time: 100000   # in seconds


